"""Shared MSP contracts, enums, and state machines."""

from .approvals import ApprovalDecision, ApprovalRequested
from .assets import AssetRef, CredentialRef
from .chat import IncidentChatContext, OperatorChatRequest, OperatorChatResponse
from .config import (
    ConfigApplyRequested,
    ConfigApplyResult,
    ConfigDesiredState,
    ConfigValidationResult,
)
from .enums import (
    ApprovalDecisionValue,
    ApprovalState,
    AssetKind,
    ChatScope,
    ChatTurnState,
    ConfigApplyState,
    HealthState,
    IncidentState,
    Severity,
)
from .events import PortfolioEvent
from .incidents import (
    DiagnosticsCollect,
    DiagnosticsResult,
    EvidenceBundle,
    IncidentRecord,
    RemediationExecute,
    RemediationResult,
)
from .state_machines import (
    APPROVAL_STATE_MACHINE,
    CHAT_TURN_STATE_MACHINE,
    CONFIG_APPLY_STATE_MACHINE,
    INCIDENT_STATE_MACHINE,
    StateMachine,
)
from .types import (
    AlertId,
    ApprovalId,
    AssetId,
    ChatSessionId,
    ClientId,
    ConfigApplyRunId,
    EventId,
    EvidenceBundleId,
    FabricId,
    IncidentId,
    JSONObject,
    JSONScalar,
    JSONValue,
    NonEmptyStr,
    RequestId,
    SnapshotId,
    TurnId,
    UTCDatetime,
    UUID4Str,
)
from .visibility import AlertRaised, HealthSnapshot

__all__ = [
    "APPROVAL_STATE_MACHINE",
    "CHAT_TURN_STATE_MACHINE",
    "CONFIG_APPLY_STATE_MACHINE",
    "INCIDENT_STATE_MACHINE",
    "AlertId",
    "AlertRaised",
    "ApprovalDecision",
    "ApprovalDecisionValue",
    "ApprovalId",
    "ApprovalRequested",
    "ApprovalState",
    "AssetId",
    "AssetKind",
    "AssetRef",
    "ChatScope",
    "ChatSessionId",
    "ChatTurnState",
    "ClientId",
    "ConfigApplyRequested",
    "ConfigApplyResult",
    "ConfigApplyRunId",
    "ConfigApplyState",
    "ConfigDesiredState",
    "ConfigValidationResult",
    "CredentialRef",
    "DiagnosticsCollect",
    "DiagnosticsResult",
    "EventId",
    "EvidenceBundle",
    "EvidenceBundleId",
    "FabricId",
    "HealthSnapshot",
    "HealthState",
    "IncidentChatContext",
    "IncidentId",
    "IncidentRecord",
    "IncidentState",
    "JSONObject",
    "JSONScalar",
    "JSONValue",
    "NonEmptyStr",
    "OperatorChatRequest",
    "OperatorChatResponse",
    "PortfolioEvent",
    "RemediationExecute",
    "RemediationResult",
    "RequestId",
    "Severity",
    "SnapshotId",
    "StateMachine",
    "TurnId",
    "UTCDatetime",
    "UUID4Str",
]
