"""phase_1_initial"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from mas_ops_api.db.types import UtcDateTime

revision = "3a5523821094"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_requests",
        sa.Column("approval_id", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("fabric_id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("action_kind", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("requested_at", UtcDateTime(), nullable=False),
        sa.Column("expires_at", UtcDateTime(), nullable=False),
        sa.Column("requested_by_agent", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("risk_summary", sa.Text(), nullable=False),
        sa.Column("decided_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("decided_at", UtcDateTime(), nullable=True),
        sa.Column("approved_at", UtcDateTime(), nullable=True),
        sa.Column("rejected_at", UtcDateTime(), nullable=True),
        sa.Column("expired_at", UtcDateTime(), nullable=True),
        sa.Column("cancelled_at", UtcDateTime(), nullable=True),
        sa.Column("executed_at", UtcDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_index(
        op.f("ix_approval_requests_client_id"),
        "approval_requests",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_requests_incident_id"),
        "approval_requests",
        ["incident_id"],
        unique=False,
    )
    op.create_table(
        "chat_sessions",
        sa.Column("chat_session_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("fabric_id", sa.String(length=36), nullable=True),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("chat_session_id"),
    )
    op.create_index(
        op.f("ix_chat_sessions_client_id"), "chat_sessions", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_sessions_incident_id"),
        "chat_sessions",
        ["incident_id"],
        unique=False,
    )
    op.create_table(
        "config_apply_runs",
        sa.Column("config_apply_run_id", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("desired_state_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("requested_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("requested_at", UtcDateTime(), nullable=False),
        sa.Column("started_at", UtcDateTime(), nullable=True),
        sa.Column("completed_at", UtcDateTime(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("config_apply_run_id"),
    )
    op.create_index(
        op.f("ix_config_apply_runs_client_id"),
        "config_apply_runs",
        ["client_id"],
        unique=False,
    )
    op.create_table(
        "config_desired_states",
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("fabric_id", sa.String(length=36), nullable=False),
        sa.Column("desired_state_version", sa.Integer(), nullable=False),
        sa.Column("tenant_metadata", sa.JSON(), nullable=False),
        sa.Column("policy", sa.JSON(), nullable=False),
        sa.Column("inventory_sources", sa.JSON(), nullable=False),
        sa.Column("notification_routes", sa.JSON(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_table(
        "config_validation_runs",
        sa.Column("config_apply_run_id", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("desired_state_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("validated_at", UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("config_apply_run_id"),
    )
    op.create_index(
        op.f("ix_config_validation_runs_client_id"),
        "config_validation_runs",
        ["client_id"],
        unique=False,
    )
    op.create_table(
        "ops_stream_events",
        sa.Column("stream_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("event_name", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column("chat_session_id", sa.String(length=36), nullable=True),
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", UtcDateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("stream_id"),
    )
    op.create_index(
        "ix_ops_stream_events_chat_session_id_stream_id",
        "ops_stream_events",
        ["chat_session_id", "stream_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ops_stream_events_client_id"),
        "ops_stream_events",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        "ix_ops_stream_events_client_id_stream_id",
        "ops_stream_events",
        ["client_id", "stream_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ops_stream_events_event_id"),
        "ops_stream_events",
        ["event_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_ops_stream_events_event_name"),
        "ops_stream_events",
        ["event_name"],
        unique=False,
    )
    op.create_index(
        "ix_ops_stream_events_incident_id_stream_id",
        "ops_stream_events",
        ["incident_id", "stream_id"],
        unique=False,
    )
    op.create_table(
        "ops_users",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_ops_users_email"), "ops_users", ["email"], unique=True)
    op.create_table(
        "portfolio_activity_events",
        sa.Column("activity_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_event_id", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("fabric_id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("activity_id"),
        sa.UniqueConstraint("client_id", "fabric_id", "source_event_id"),
    )
    op.create_index(
        op.f("ix_portfolio_activity_events_client_id"),
        "portfolio_activity_events",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_activity_events_fabric_id"),
        "portfolio_activity_events",
        ["fabric_id"],
        unique=False,
    )
    op.create_index(
        "ix_portfolio_activity_events_incident_id",
        "portfolio_activity_events",
        ["incident_id"],
        unique=False,
    )
    op.create_table(
        "portfolio_assets",
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("fabric_id", sa.String(length=36), nullable=False),
        sa.Column("asset_kind", sa.String(length=32), nullable=False),
        sa.Column("vendor", sa.String(length=120), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("mgmt_address", sa.String(length=255), nullable=True),
        sa.Column("site", sa.String(length=255), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("health_state", sa.String(length=32), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_index(
        op.f("ix_portfolio_assets_client_id"),
        "portfolio_assets",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_assets_fabric_id"),
        "portfolio_assets",
        ["fabric_id"],
        unique=False,
    )
    op.create_table(
        "portfolio_clients",
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("fabric_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("open_alert_count", sa.Integer(), nullable=False),
        sa.Column("critical_asset_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_index(
        op.f("ix_portfolio_clients_fabric_id"),
        "portfolio_clients",
        ["fabric_id"],
        unique=False,
    )
    op.create_table(
        "portfolio_incidents",
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("fabric_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("opened_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("incident_id"),
    )
    op.create_index(
        op.f("ix_portfolio_incidents_client_id"),
        "portfolio_incidents",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_incidents_fabric_id"),
        "portfolio_incidents",
        ["fabric_id"],
        unique=False,
    )
    op.create_table(
        "chat_turns",
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("chat_session_id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("submitted_at", UtcDateTime(), nullable=False),
        sa.Column("completed_at", UtcDateTime(), nullable=True),
        sa.Column("approval_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_session_id"], ["chat_sessions.chat_session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("turn_id"),
    )
    op.create_index(
        op.f("ix_chat_turns_chat_session_id"),
        "chat_turns",
        ["chat_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_turns_request_id"), "chat_turns", ["request_id"], unique=True
    )
    op.create_table(
        "ops_sessions",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("last_seen_at", UtcDateTime(), nullable=False),
        sa.Column("idle_expires_at", UtcDateTime(), nullable=False),
        sa.Column("absolute_expires_at", UtcDateTime(), nullable=False),
        sa.Column("revoked_at", UtcDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["ops_users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_ops_sessions_session_token_hash"),
        "ops_sessions",
        ["session_token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_ops_sessions_user_id"), "ops_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "ops_user_client_access",
        sa.Column("access_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["ops_users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("access_id"),
        sa.UniqueConstraint("user_id", "client_id"),
    )
    op.create_index(
        op.f("ix_ops_user_client_access_client_id"),
        "ops_user_client_access",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ops_user_client_access_user_id"),
        "ops_user_client_access",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "ops_user_passwords",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["ops_users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "chat_messages",
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("chat_session_id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_session_id"], ["chat_sessions.chat_session_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["chat_turns.turn_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_index(
        op.f("ix_chat_messages_chat_session_id"),
        "chat_messages",
        ["chat_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_turn_id"), "chat_messages", ["turn_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_turn_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_chat_session_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_table("ops_user_passwords")
    op.drop_index(
        op.f("ix_ops_user_client_access_user_id"), table_name="ops_user_client_access"
    )
    op.drop_index(
        op.f("ix_ops_user_client_access_client_id"), table_name="ops_user_client_access"
    )
    op.drop_table("ops_user_client_access")
    op.drop_index(op.f("ix_ops_sessions_user_id"), table_name="ops_sessions")
    op.drop_index(op.f("ix_ops_sessions_session_token_hash"), table_name="ops_sessions")
    op.drop_table("ops_sessions")
    op.drop_index(op.f("ix_chat_turns_request_id"), table_name="chat_turns")
    op.drop_index(op.f("ix_chat_turns_chat_session_id"), table_name="chat_turns")
    op.drop_table("chat_turns")
    op.drop_index(
        op.f("ix_portfolio_incidents_fabric_id"), table_name="portfolio_incidents"
    )
    op.drop_index(
        op.f("ix_portfolio_incidents_client_id"), table_name="portfolio_incidents"
    )
    op.drop_table("portfolio_incidents")
    op.drop_index(
        op.f("ix_portfolio_clients_fabric_id"), table_name="portfolio_clients"
    )
    op.drop_table("portfolio_clients")
    op.drop_index(op.f("ix_portfolio_assets_fabric_id"), table_name="portfolio_assets")
    op.drop_index(op.f("ix_portfolio_assets_client_id"), table_name="portfolio_assets")
    op.drop_table("portfolio_assets")
    op.drop_index(
        "ix_portfolio_activity_events_incident_id",
        table_name="portfolio_activity_events",
    )
    op.drop_index(
        op.f("ix_portfolio_activity_events_fabric_id"),
        table_name="portfolio_activity_events",
    )
    op.drop_index(
        op.f("ix_portfolio_activity_events_client_id"),
        table_name="portfolio_activity_events",
    )
    op.drop_table("portfolio_activity_events")
    op.drop_index(op.f("ix_ops_users_email"), table_name="ops_users")
    op.drop_table("ops_users")
    op.drop_index(
        "ix_ops_stream_events_incident_id_stream_id", table_name="ops_stream_events"
    )
    op.drop_index(
        op.f("ix_ops_stream_events_event_name"), table_name="ops_stream_events"
    )
    op.drop_index(op.f("ix_ops_stream_events_event_id"), table_name="ops_stream_events")
    op.drop_index(
        "ix_ops_stream_events_client_id_stream_id", table_name="ops_stream_events"
    )
    op.drop_index(
        op.f("ix_ops_stream_events_client_id"), table_name="ops_stream_events"
    )
    op.drop_index(
        "ix_ops_stream_events_chat_session_id_stream_id", table_name="ops_stream_events"
    )
    op.drop_table("ops_stream_events")
    op.drop_index(
        op.f("ix_config_validation_runs_client_id"), table_name="config_validation_runs"
    )
    op.drop_table("config_validation_runs")
    op.drop_table("config_desired_states")
    op.drop_index(
        op.f("ix_config_apply_runs_client_id"), table_name="config_apply_runs"
    )
    op.drop_table("config_apply_runs")
    op.drop_index(op.f("ix_chat_sessions_incident_id"), table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_client_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index(
        op.f("ix_approval_requests_incident_id"), table_name="approval_requests"
    )
    op.drop_index(
        op.f("ix_approval_requests_client_id"), table_name="approval_requests"
    )
    op.drop_table("approval_requests")
    # ### end Alembic commands ###
