# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mas_proto.runtime.v1 import runtime_pb2 as mas__proto_dot_runtime_dot_v1_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mas_proto/runtime/v1/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transport = channel.stream_stream(
                '/mas.runtime.v1.RuntimeService/Transport',
                request_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ClientEvent.SerializeToString,
                response_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ServerEvent.FromString,
                _registered_method=True)
        self.Send = channel.unary_unary(
                '/mas.runtime.v1.RuntimeService/Send',
                request_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.SendRequest.SerializeToString,
                response_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.SendResponse.FromString,
                _registered_method=True)
        self.Request = channel.unary_unary(
                '/mas.runtime.v1.RuntimeService/Request',
                request_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.RequestRequest.SerializeToString,
                response_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.RequestResponse.FromString,
                _registered_method=True)
        self.Reply = channel.unary_unary(
                '/mas.runtime.v1.RuntimeService/Reply',
                request_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ReplyRequest.SerializeToString,
                response_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ReplyResponse.FromString,
                _registered_method=True)
        self.Discover = channel.unary_unary(
                '/mas.runtime.v1.RuntimeService/Discover',
                request_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.DiscoverResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/mas.runtime.v1.RuntimeService/GetState',
                request_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.GetStateRequest.SerializeToString,
                response_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.UpdateState = channel.unary_unary(
                '/mas.runtime.v1.RuntimeService/UpdateState',
                request_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.UpdateStateRequest.SerializeToString,
                response_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.UpdateStateResponse.FromString,
                _registered_method=True)
        self.ResetState = channel.unary_unary(
                '/mas.runtime.v1.RuntimeService/ResetState',
                request_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ResetStateRequest.SerializeToString,
                response_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ResetStateResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transport(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transport': grpc.stream_stream_rpc_method_handler(
                    servicer.Transport,
                    request_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ClientEvent.FromString,
                    response_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ServerEvent.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.SendRequest.FromString,
                    response_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.SendResponse.SerializeToString,
            ),
            'Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Request,
                    request_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.RequestRequest.FromString,
                    response_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.RequestResponse.SerializeToString,
            ),
            'Reply': grpc.unary_unary_rpc_method_handler(
                    servicer.Reply,
                    request_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ReplyRequest.FromString,
                    response_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ReplyResponse.SerializeToString,
            ),
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.DiscoverRequest.FromString,
                    response_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.DiscoverResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.GetStateRequest.FromString,
                    response_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.GetStateResponse.SerializeToString,
            ),
            'UpdateState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateState,
                    request_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.UpdateStateRequest.FromString,
                    response_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.UpdateStateResponse.SerializeToString,
            ),
            'ResetState': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetState,
                    request_deserializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ResetStateRequest.FromString,
                    response_serializer=mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ResetStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mas.runtime.v1.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mas.runtime.v1.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transport(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mas.runtime.v1.RuntimeService/Transport',
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ClientEvent.SerializeToString,
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ServerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mas.runtime.v1.RuntimeService/Send',
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.SendRequest.SerializeToString,
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mas.runtime.v1.RuntimeService/Request',
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.RequestRequest.SerializeToString,
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.RequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mas.runtime.v1.RuntimeService/Reply',
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ReplyRequest.SerializeToString,
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ReplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mas.runtime.v1.RuntimeService/Discover',
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.DiscoverRequest.SerializeToString,
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mas.runtime.v1.RuntimeService/GetState',
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.GetStateRequest.SerializeToString,
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mas.runtime.v1.RuntimeService/UpdateState',
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.UpdateStateRequest.SerializeToString,
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.UpdateStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mas.runtime.v1.RuntimeService/ResetState',
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ResetStateRequest.SerializeToString,
            mas__proto_dot_runtime_dot_v1_dot_runtime__pb2.ResetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
