"""Generate the MAS Ops UI OpenAPI snapshot and TypeScript client."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from mas_ops_api.app import create_app
from mas_ops_api.settings import OpsApiSettings


ROOT = Path(__file__).resolve().parents[3]
OPENAPI_PATH = ROOT / "apps/mas-ops-api/openapi.json"
GENERATED_DIR = ROOT / "apps/mas-ops-ui/src/api/generated"


@dataclass(frozen=True)
class OperationDefinition:
    """Human-friendly method metadata for generated client methods."""

    method: str
    path: str
    name: str


OPERATIONS = [
    OperationDefinition("GET", "/approvals", "listApprovals"),
    OperationDefinition(
        "POST", "/approvals/{approval_id}/decision", "submitApprovalDecision"
    ),
    OperationDefinition("GET", "/assets/{asset_id}", "getAsset"),
    OperationDefinition("GET", "/assets/{asset_id}/activity", "listAssetActivity"),
    OperationDefinition("POST", "/auth/login", "login"),
    OperationDefinition("POST", "/auth/logout", "logout"),
    OperationDefinition("GET", "/auth/session", "restoreSession"),
    OperationDefinition("POST", "/chat/sessions", "createChatSession"),
    OperationDefinition("GET", "/chat/sessions/{chat_session_id}", "getChatSession"),
    OperationDefinition(
        "POST", "/chat/sessions/{chat_session_id}/messages", "appendChatMessage"
    ),
    OperationDefinition("GET", "/clients", "listClients"),
    OperationDefinition("GET", "/clients/{client_id}", "getClient"),
    OperationDefinition("GET", "/clients/{client_id}/activity", "listClientActivity"),
    OperationDefinition("GET", "/clients/{client_id}/assets", "listClientAssets"),
    OperationDefinition(
        "POST", "/clients/{client_id}/config/apply", "applyDesiredState"
    ),
    OperationDefinition(
        "GET", "/clients/{client_id}/config/desired-state", "getDesiredState"
    ),
    OperationDefinition(
        "POST",
        "/clients/{client_id}/config/runs/{config_apply_run_id}/cancel",
        "cancelConfigApplyRun",
    ),
    OperationDefinition("GET", "/clients/{client_id}/config/runs", "listConfigRuns"),
    OperationDefinition(
        "PUT", "/clients/{client_id}/config/desired-state", "replaceDesiredState"
    ),
    OperationDefinition(
        "POST", "/clients/{client_id}/config/validate", "validateDesiredState"
    ),
    OperationDefinition("GET", "/clients/{client_id}/incidents", "listClientIncidents"),
    OperationDefinition("GET", "/incidents/{incident_id}", "getIncident"),
    OperationDefinition(
        "GET", "/incidents/{incident_id}/activity", "listIncidentActivity"
    ),
]

STREAM_OPERATIONS = [
    OperationDefinition("GET", "/streams/portfolio", "portfolioStream"),
    OperationDefinition("GET", "/streams/clients/{client_id}", "clientStream"),
    OperationDefinition("GET", "/streams/incidents/{incident_id}", "incidentStream"),
    OperationDefinition("GET", "/streams/chat/{chat_session_id}", "chatStream"),
]


def main() -> None:
    """Generate OpenAPI artifacts consumed by the UI."""

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    openapi = create_app(OpsApiSettings()).openapi()
    OPENAPI_PATH.write_text(
        json.dumps(openapi, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (GENERATED_DIR / "types.ts").write_text(render_types(openapi), encoding="utf-8")
    (GENERATED_DIR / "client.ts").write_text(render_client(openapi), encoding="utf-8")
    (GENERATED_DIR / "index.ts").write_text(
        'export * from "./client";\nexport * from "./types";\n',
        encoding="utf-8",
    )
    (GENERATED_DIR / "README.md").write_text(
        "# Generated API Client\n\n"
        "Regenerate these files from the FastAPI app with:\n\n"
        "```bash\n"
        "uv run python apps/mas-ops-ui/scripts/generate_openapi_client.py\n"
        "```\n",
        encoding="utf-8",
    )


def render_types(openapi: dict[str, Any]) -> str:
    """Render TypeScript aliases for OpenAPI component schemas."""

    schemas = openapi.get("components", {}).get("schemas", {})
    lines = [
        "// Generated by apps/mas-ops-ui/scripts/generate_openapi_client.py",
        "// Do not edit by hand.",
        "",
    ]
    for schema_name in sorted(schemas):
        ts_name = sanitize_type_name(schema_name)
        body = render_type_alias(ts_name, schemas[schema_name])
        lines.append(body)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_client(openapi: dict[str, Any]) -> str:
    """Render a minimal fetch-based TypeScript client."""

    lines = [
        "// Generated by apps/mas-ops-ui/scripts/generate_openapi_client.py",
        "// Do not edit by hand.",
        "",
        "import type {",
    ]
    imported_types = collect_imported_types(openapi)
    for type_name in imported_types:
        lines.append(f"  {type_name},")
    lines.extend(
        [
            '} from "./types";',
            "",
            "export class ApiError extends Error {",
            "  constructor(",
            "    message: string,",
            "    readonly status: number,",
            "    readonly body: unknown,",
            "  ) {",
            "    super(message);",
            '    this.name = "ApiError";',
            "  }",
            "}",
            "",
            "export type MasOpsApiClientOptions = {",
            "  baseUrl?: string;",
            "  fetch?: typeof fetch;",
            "  headers?: HeadersInit;",
            "};",
            "",
            "export type StreamRequestOptions = {",
            "  lastEventId?: string | null;",
            "  replayOnly?: boolean;",
            "};",
            "",
            "function resolveBaseUrl(baseUrl?: string): string {",
            "  if (baseUrl && baseUrl.length > 0) {",
            "    return baseUrl.replace(/\\/$/, '');",
            "  }",
            "  if (typeof import.meta !== 'undefined' && import.meta.env?.VITE_MAS_OPS_API_BASE_URL) {",
            "    return import.meta.env.VITE_MAS_OPS_API_BASE_URL.replace(/\\/$/, '');",
            "  }",
            "  return 'http://127.0.0.1:8080';",
            "}",
            "",
            "async function parseErrorBody(response: Response): Promise<unknown> {",
            "  const contentType = response.headers.get('content-type') ?? '';",
            "  if (contentType.includes('application/json')) {",
            "    return await response.json();",
            "  }",
            "  const text = await response.text();",
            "  return text.length > 0 ? text : null;",
            "}",
            "",
            "type JsonRequest = {",
            "  method: string;",
            "  path: string;",
            "  body?: unknown;",
            "};",
            "",
            "type StreamRequest = {",
            "  path: string;",
            "  lastEventId?: string | null;",
            "  replayOnly?: boolean;",
            "};",
            "",
            "export class MasOpsApiClient {",
            "  readonly baseUrl: string;",
            "  private readonly fetchImpl?: typeof fetch;",
            "  private readonly headers?: HeadersInit;",
            "",
            "  constructor(options: MasOpsApiClientOptions = {}) {",
            "    this.baseUrl = resolveBaseUrl(options.baseUrl);",
            "    this.fetchImpl = options.fetch;",
            "    this.headers = options.headers;",
            "  }",
            "",
            "  private resolveFetchImpl(): typeof fetch {",
            "    if (this.fetchImpl !== undefined) {",
            "      return this.fetchImpl;",
            "    }",
            "    if (typeof globalThis.fetch !== 'function') {",
            '      throw new Error("MAS Ops API client requires a global fetch implementation.");',
            "    }",
            "    return globalThis.fetch.bind(globalThis);",
            "  }",
            "",
            "  private buildUrl(path: string, query?: URLSearchParams): string {",
            "    const suffix = query && query.size > 0 ? `?${query.toString()}` : '';",
            "    return `${this.baseUrl}${path}${suffix}`;",
            "  }",
            "",
            "  private async requestJson<T>({ method, path, body }: JsonRequest): Promise<T> {",
            "    const response = await this.resolveFetchImpl()(this.buildUrl(path), {",
            "      method,",
            "      credentials: 'include',",
            "      headers: {",
            "        accept: 'application/json',",
            "        ...(body === undefined ? {} : { 'content-type': 'application/json' }),",
            "        ...(this.headers ?? {}),",
            "      },",
            "      body: body === undefined ? undefined : JSON.stringify(body),",
            "    });",
            "    if (!response.ok) {",
            "      throw new ApiError(",
            "        `${method} ${path} failed with ${response.status}`,",
            "        response.status,",
            "        await parseErrorBody(response),",
            "      );",
            "    }",
            "    return (await response.json()) as T;",
            "  }",
            "",
            "  private async requestVoid({ method, path, body }: JsonRequest): Promise<void> {",
            "    const response = await this.resolveFetchImpl()(this.buildUrl(path), {",
            "      method,",
            "      credentials: 'include',",
            "      headers: {",
            "        accept: 'application/json',",
            "        ...(body === undefined ? {} : { 'content-type': 'application/json' }),",
            "        ...(this.headers ?? {}),",
            "      },",
            "      body: body === undefined ? undefined : JSON.stringify(body),",
            "    });",
            "    if (!response.ok) {",
            "      throw new ApiError(",
            "        `${method} ${path} failed with ${response.status}`,",
            "        response.status,",
            "        await parseErrorBody(response),",
            "      );",
            "    }",
            "  }",
            "",
            "  private async requestStream({ path, lastEventId, replayOnly = false }: StreamRequest): Promise<Response> {",
            "    const query = new URLSearchParams();",
            "    if (replayOnly) {",
            "      query.set('replay_only', 'true');",
            "    }",
            "    return this.resolveFetchImpl()(this.buildUrl(path, query), {",
            "      method: 'GET',",
            "      credentials: 'include',",
            "      headers: {",
            "        ...(this.headers ?? {}),",
            "        ...(lastEventId ? { 'Last-Event-ID': lastEventId } : {}),",
            "      },",
            "    });",
            "  }",
            "",
        ]
    )
    for operation in OPERATIONS:
        lines.extend(render_operation(openapi, operation))
        lines.append("")
    for operation in STREAM_OPERATIONS:
        lines.extend(render_stream_operation(openapi, operation))
        lines.append("")
    lines.append("}")
    return "\n".join(lines).rstrip() + "\n"


def collect_imported_types(openapi: dict[str, Any]) -> list[str]:
    """Return type aliases used by the generated client methods."""

    seen: set[str] = set()
    for operation in OPERATIONS:
        raw_operation = openapi["paths"][operation.path][operation.method.lower()]
        request_body = (
            raw_operation.get("requestBody", {})
            .get("content", {})
            .get("application/json", {})
            .get("schema")
        )
        if request_body is not None:
            seen.update(collect_ref_types(request_body))
        response_schema = get_success_response_schema(raw_operation)
        if response_schema is not None:
            seen.update(collect_ref_types(response_schema))
        for parameter in raw_operation.get("parameters", []):
            seen.update(collect_ref_types(parameter.get("schema", {})))
    return sorted(seen)


def collect_ref_types(schema: dict[str, Any]) -> set[str]:
    """Collect referenced component schema names from a schema node."""

    refs: set[str] = set()
    ref = schema.get("$ref")
    if ref is not None:
        refs.add(sanitize_type_name(ref.rsplit("/", 1)[-1]))
    for key in ("items", "additionalProperties"):
        value = schema.get(key)
        if isinstance(value, dict):
            refs.update(collect_ref_types(value))
    for key in ("anyOf", "allOf", "oneOf"):
        for item in schema.get(key, []):
            if isinstance(item, dict):
                refs.update(collect_ref_types(item))
    for property_schema in schema.get("properties", {}).values():
        if isinstance(property_schema, dict):
            refs.update(collect_ref_types(property_schema))
    return refs


def render_operation(
    openapi: dict[str, Any], operation_definition: OperationDefinition
) -> list[str]:
    """Render one generated client method."""

    operation = openapi["paths"][operation_definition.path][
        operation_definition.method.lower()
    ]
    parameters = operation.get("parameters", [])
    path_parameters = order_path_parameters(
        operation_definition.path,
        [item for item in parameters if item.get("in") == "path"],
    )
    request_body = (
        operation.get("requestBody", {})
        .get("content", {})
        .get("application/json", {})
        .get("schema")
    )
    response_schema = get_success_response_schema(operation)
    return_type = (
        "void"
        if response_schema is None
        else render_schema_type(response_schema, indent=0)
    )
    signature_parts: list[str] = []

    for parameter in path_parameters:
        argument_name = to_camel_case(parameter["name"])
        signature_parts.append(
            f"{argument_name}: {render_schema_type(parameter['schema'], indent=0)}"
        )

    if request_body is not None:
        signature_parts.append(f"body: {render_schema_type(request_body, indent=0)}")

    method_lines = [
        f"  async {operation_definition.name}({', '.join(signature_parts)}): Promise<{return_type}> {{"
    ]
    path_template = render_path_template(operation_definition.path, path_parameters)
    request_method = (
        "requestVoid" if response_schema is None else f"requestJson<{return_type}>"
    )
    method_lines.append(f"    return this.{request_method}({{")
    method_lines.append(f"      method: '{operation_definition.method}',")
    method_lines.append(f"      path: {path_template},")
    if request_body is not None:
        method_lines.append("      body,")
    method_lines.append("    });")
    method_lines.append("  }")
    return method_lines


def render_stream_operation(
    openapi: dict[str, Any], operation_definition: OperationDefinition
) -> list[str]:
    """Render generated helpers for SSE replay and live URLs."""

    operation = openapi["paths"][operation_definition.path][
        operation_definition.method.lower()
    ]
    parameters = operation.get("parameters", [])
    path_parameters = order_path_parameters(
        operation_definition.path,
        [item for item in parameters if item.get("in") == "path"],
    )
    signature_parts = [
        f"{to_camel_case(parameter['name'])}: {render_schema_type(parameter['schema'], indent=0)}"
        for parameter in path_parameters
    ]
    options_signature = "options: StreamRequestOptions = {}"
    url_method_name = (
        "get"
        + operation_definition.name[:1].upper()
        + operation_definition.name[1:]
        + "Url"
    )
    fetch_method_name = (
        "fetch" + operation_definition.name[:1].upper() + operation_definition.name[1:]
    )
    path_template = render_path_template(operation_definition.path, path_parameters)

    url_signature = signature_parts.copy()
    fetch_signature = signature_parts + [options_signature]
    return [
        f"  {url_method_name}({', '.join(url_signature)}): string {{"
        if url_signature
        else f"  {url_method_name}(): string {{",
        f"    return this.buildUrl({path_template});",
        "  }",
        "",
        f"  {fetch_method_name}({', '.join(fetch_signature)}): Promise<Response> {{"
        if fetch_signature
        else f"  {fetch_method_name}(): Promise<Response> {{",
        "    return this.requestStream({",
        f"      path: {path_template},",
        "      ...options,",
        "    });",
        "  }",
    ]


def get_success_response_schema(operation: dict[str, Any]) -> dict[str, Any] | None:
    """Return the first JSON success schema for an operation."""

    for status_code, response in sorted(operation.get("responses", {}).items()):
        if not status_code.startswith("2"):
            continue
        schema = response.get("content", {}).get("application/json", {}).get("schema")
        if schema is not None:
            return schema
    return None


def render_path_template(path: str, path_parameters: list[dict[str, Any]]) -> str:
    """Render a template literal path with encoded path parameters."""

    rendered = path
    for parameter in path_parameters:
        name = parameter["name"]
        camel_name = to_camel_case(name)
        rendered = rendered.replace(
            "{" + name + "}",
            "${encodeURIComponent(String(" + camel_name + "))}",
        )
    return f"`{rendered}`"


def order_path_parameters(
    path: str,
    path_parameters: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Return path parameters in URI-template order instead of schema order."""

    ordered_names = re.findall(r"{([^}]+)}", path)
    parameters_by_name = {
        parameter["name"]: parameter
        for parameter in path_parameters
        if isinstance(parameter.get("name"), str)
    }
    return [
        parameters_by_name[name] for name in ordered_names if name in parameters_by_name
    ]


def render_type_alias(type_name: str, schema: dict[str, Any]) -> str:
    """Render one exported TypeScript type alias."""

    if type_name in {"JSONValueInput", "JSONValueOutput"}:
        return render_recursive_json_types(type_name)

    rendered = render_schema_type(schema, indent=0)
    return f"export type {type_name} = {rendered};"


def render_recursive_json_types(type_name: str) -> str:
    """Render recursive JSON value helpers without circular alias errors."""

    object_name = type_name.replace("Value", "Object")
    array_name = type_name.replace("Value", "Array")
    return "\n".join(
        [
            (
                f"export type {type_name} = boolean | number | string | "
                f"{array_name} | {object_name} | null;"
            ),
            "",
            f"export interface {object_name} {{",
            f"  [key: string]: {type_name};",
            "}",
            "",
            f"export interface {array_name} extends Array<{type_name}> {{}}",
        ]
    )


def render_schema_type(schema: dict[str, Any], indent: int) -> str:
    """Render a TypeScript type from one OpenAPI schema node."""

    ref = schema.get("$ref")
    if ref is not None:
        return sanitize_type_name(ref.rsplit("/", 1)[-1])

    variants = schema.get("anyOf") or schema.get("oneOf")
    if variants:
        rendered_variants = [
            render_schema_type(item, indent=indent) for item in variants if item
        ]
        return " | ".join(unique(rendered_variants))

    all_of = schema.get("allOf")
    if all_of:
        rendered_variants = [
            render_schema_type(item, indent=indent) for item in all_of if item
        ]
        return " & ".join(unique(rendered_variants))

    enum_values = schema.get("enum")
    if enum_values:
        return " | ".join(json.dumps(value) for value in enum_values)

    schema_type = schema.get("type")
    if schema_type == "array":
        item_type = render_schema_type(schema.get("items", {}), indent=indent)
        return f"Array<{item_type}>"
    if schema_type == "object":
        properties = schema.get("properties")
        additional = schema.get("additionalProperties")
        if properties:
            return render_object_type(schema, indent)
        if additional is True:
            return "Record<string, unknown>"
        if additional is False:
            return "Record<string, never>"
        if isinstance(additional, dict):
            return (
                "Record<string, " + render_schema_type(additional, indent=indent) + ">"
            )
        return "Record<string, unknown>"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "string":
        return "string"
    return "unknown"


def render_object_type(schema: dict[str, Any], indent: int) -> str:
    """Render a multi-line TypeScript object type."""

    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    child_indent = indent + 2
    padding = " " * child_indent
    closing_padding = " " * indent
    lines = ["{"]
    for property_name in sorted(properties):
        property_schema = properties[property_name]
        suffix = "" if property_name in required else "?"
        rendered_key = (
            property_name
            if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", property_name)
            else json.dumps(property_name)
        )
        rendered_value = render_schema_type(property_schema, indent=child_indent)
        lines.append(f"{padding}{rendered_key}{suffix}: {rendered_value};")
    lines.append(f"{closing_padding}}}")
    return "\n".join(lines)


def sanitize_type_name(raw_name: str) -> str:
    """Convert an OpenAPI schema name into a valid TypeScript type alias name."""

    parts = re.split(r"[^0-9A-Za-z]+", raw_name)
    sanitized = "".join(part[:1].upper() + part[1:] for part in parts if part)
    if not sanitized:
        return "GeneratedType"
    if sanitized[0].isdigit():
        return f"Type{sanitized}"
    return sanitized


def to_camel_case(raw_name: str) -> str:
    """Convert an OpenAPI parameter name into a camelCase identifier."""

    parts = re.split(r"[^0-9A-Za-z]+", raw_name)
    words = [part for part in parts if part]
    if not words:
        return "value"
    first, *rest = words
    return (
        first[:1].lower()
        + first[1:]
        + "".join(part[:1].upper() + part[1:] for part in rest)
    )


def unique(items: list[str]) -> list[str]:
    """Deduplicate list items while preserving order."""

    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        result.append(item)
    return result


if __name__ == "__main__":
    main()
